[theme]
backgroundColor = "#FFFFFF"
textColor = "#4A5568"
primaryColor = "#FF6B6B"
secondaryBackgroundColor = "#F0F2F6"  # Colore di sfondo secondario
font = "sans serif"  # Puoi scegliere tra 'sans serif', 'serif', e 'monospace'
