[theme]
primaryColor="#6C63FF"           # Colore principale moderno e vivace
backgroundColor="#F8F9FD"        # Sfondo principale chiaro con una leggera tinta blu
secondaryBackgroundColor="#FFFFFF" # Sfondo secondario bianco puro
textColor="#1E293B"              # Colore testo scuro leggermente bluastro
font="Inter"                     # Font moderno e leggibile
