[theme]
primaryColor = "#6C63FF"
backgroundColor = "#F8F9FD"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1E293B"
font = "Inter"

# Additional settings
[theme.components]
stButton.height = "3rem"
stSelectbox.height = "3rem"
stTextInput.height = "3rem"
